### ISSUE TITLE
Maybe join forces?

### ISSUE THREAD

**Issue by flying-sheep** [rst-js/rst-js#6]
Hi, this seems pretty dead, but maybe we can make it less so.

For my private page I created something similar in scope. It consists of three parts:

1. [Parsing to a custom data structure](https://github.com/flying-sheep/phil.red/tree/0f9557fc67f87ebf3640c7443233aabf828249e6/src/markup)

   - [MarkupDocument](https://github.com/flying-sheep/phil.red/blob/0f9557fc67f87ebf3640c7443233aabf828249e6/src/markup/MarkupDocument.ts) is the module holding functions for all known document elements. It’s roughly a DocumentTree, but not quite. We could close the gap.
   - [rst](https://github.com/flying-sheep/phil.red/blob/0f9557fc67f87ebf3640c7443233aabf828249e6/src/markup/rst.tsx) and [md](https://github.com/flying-sheep/phil.red/blob/0f9557fc67f87ebf3640c7443233aabf828249e6/src/markup/md.tsx) are adapters the make 3rd party parsers emit the above tree. Because it’s cute, I use a custom JSX factory so one can directly use JSX syntax to emit plain data in here.

2. [rollup-plugin-renderdoc](https://github.com/flying-sheep/phil.red/blob/0f9557fc67f87ebf3640c7443233aabf828249e6/src/build-tools/rollup-plugin-renderdoc.ts) is the analog to your Webpack loader for Rollup. Just a few lines of code to dispatch one of above parser adapters based on the file extension. Since the parser adapters simply emit plain objects, it’s easy to base both a webpack loader and a rollup loader on them.

3. [Markup components](https://github.com/flying-sheep/phil.red/tree/0f9557fc67f87ebf3640c7443233aabf828249e6/src/components/markup) to render markup documents

   - [Markup](https://github.com/flying-sheep/phil.red/blob/0f9557fc67f87ebf3640c7443233aabf828249e6/src/components/markup/Markup.tsx) is the Component wrapping a complete document and not very interesting
   - [MarkupNodeComponent](https://github.com/flying-sheep/phil.red/blob/0f9557fc67f87ebf3640c7443233aabf828249e6/src/components/markup/MarkupNodeComponent.tsx) dispatch on the type and render them to React (in this case MiUI, but easily adaptable)

I’d be willing to join forces to make my and your stuff one (or several) modules, but only as long as we use TypeScript (No going back to JS for me!)

**Comment by tricoder42** [comment]
Hi @flying-sheep, thank you for your interest! I wish you were around a year ago. At the moment I don't have any extra time to work on this project anymore. I barely find time to manage my other project, https://github.com/lingui/js-lingui

All I can do is transfer any repositories you might find usable (if you want to keep the name). Otherwise feel free to clone, copy-paste, tear apart, whatever you find useful.

Good luck! 👍 

PS: Typescript FTW! 🚀

**Comment by flying-sheep** [comment]
> I barely find time to manage my other project, lingui/js-lingui

I know that feel, I don’t have much time myself sadly. Thanks for the offer. Like it is, I’ll probably keep having it in-tree of my page.

**Comment by tricoder42** [comment]
Cool, good luck!
